name: Get Commits After Last Tag
on:
  push:
    tags:
      - '*'

jobs:
  get_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "youremail@example.com"

    - name: Get the last tag
      id: last_tag
      run: |
        last_tag=$(git describe --abbrev=0 --tags)
        echo "Last tag: $last_tag"
        echo "::set-output name=tag::$last_tag"

    - name: Get commits since the last tag
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        last_tag="${{ steps.last_tag.outputs.tag }}"
        echo "Last tag: $last_tag"
        git log --pretty=format:"%H" $last_tag..HEAD > commits.txt
        echo "Commits after $last_tag:"
        cat commits.txt
