name: Get Commits After Last Tag
on:
  push:
    tags:
      - '*'

jobs:
  get_commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "youremail@example.com"

    - name: Get the last two tags
      id: last_two_tags
      run: |
        git fetch --tags
        tags=$(git tag --sort=-creatordate)
        last_two_tags=($(echo "$tags" | head -n 2))
        echo "Last two tags: ${last_two_tags[@]}"
        echo "::set-output name=tags::${last_two_tags[@]}"

    - name: Get commits between the last two tags
      id: commit_messages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        tags=(${{ steps.last_two_tags.outputs.tags }})
        penultimate_tag=${tags[1]}
        last_tag=${tags[0]}
        echo "Penultimate tag: $penultimate_tag"
        echo "Last tag: $last_tag"
        git log --pretty=format:"%H %s" e114bc3eda41b301c8575c44d48a9e804e4bf8d8..$HEAD | while read line; do echo "::debug::${line}"; done
