on:
  workflow_dispatch:
    inputs:
      release_version:
        description: ‘Version to be released. Git tag with this name will be created.’
        required: true
        default: ‘0.0.0’
jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.event.inputs.release_version }} \
              --repo=“$GITHUB_REPOSITORY” \
              --generate-notes
