name: Update Release Description with Changelog

on:
  release:
    types:
      - created
jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.event.inputs.release_version }} \
              --repo=“$GITHUB_REPOSITORY” \
              --generate-notes
